//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibFLExBridgeChorusPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibFLExBridgeChorusPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canonical book number is out of range..
        /// </summary>
        internal static string kCanonicalBookNumberOutOfRange {
            get {
                return ResourceManager.GetString("kCanonicalBookNumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string kCloseCurlyBrace {
            get {
                return ResourceManager.GetString("kCloseCurlyBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field.
        /// </summary>
        internal static string kCustomFieldLabel {
            get {
                return ResourceManager.GetString("kCustomFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string kLexEntryClassLabel {
            get {
                return ResourceManager.GetString("kLexEntryClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;modelversion&quot;: .
        /// </summary>
        internal static string kModelVersion {
            get {
                return ResourceManager.GetString("kModelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ownerguid&apos; may not be an empty string.
        /// </summary>
        internal static string kOwnerGuidEmpty {
            get {
                return ResourceManager.GetString("kOwnerGuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string kPossibilityItemLabel {
            get {
                return ResourceManager.GetString("kPossibilityItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string kPossibilityListClassLabel {
            get {
                return ResourceManager.GetString("kPossibilityListClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversal Entry.
        /// </summary>
        internal static string kReversalEntryClassLabel {
            get {
                return ResourceManager.GetString("kReversalEntryClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Notebook Record.
        /// </summary>
        internal static string kRnGenericRecLabel {
            get {
                return ResourceManager.GetString("kRnGenericRecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripture Book.
        /// </summary>
        internal static string kScrBookClassLabel {
            get {
                return ResourceManager.GetString("kScrBookClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripture Section.
        /// </summary>
        internal static string kScrSectionClassLabel {
            get {
                return ResourceManager.GetString("kScrSectionClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}:{2}-{3}:{4}.
        /// </summary>
        internal static string kScrSectionMultiChapter {
            get {
                return ResourceManager.GetString("kScrSectionMultiChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}:{2}-{3}.
        /// </summary>
        internal static string kScrSectionOneChapter {
            get {
                return ResourceManager.GetString("kScrSectionOneChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discourse Chart.
        /// </summary>
        internal static string ksDiscourseChart {
            get {
                return ResourceManager.GetString("ksDiscourseChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ksEnvironment {
            get {
                return ResourceManager.GetString("ksEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other users of this repository (most recently {0}) are using a different version of FieldWorks. Changes from users with more recent versions will not be merged into projects using older versions. We strongly recommend that all users upgrade to the same version as soon as possible..
        /// </summary>
        internal static string ksOtherRevisionWarning {
            get {
                return ResourceManager.GetString("ksOtherRevisionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string kStyleLabel {
            get {
                return ResourceManager.GetString("kStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string kTextClassLabel {
            get {
                return ResourceManager.GetString("kTextClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [unidentified].
        /// </summary>
        internal static string kUnidentifiedLabel {
            get {
                return ResourceManager.GetString("kUnidentifiedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [untitled].
        /// </summary>
        internal static string kUnTitled {
            get {
                return ResourceManager.GetString("kUnTitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordform.
        /// </summary>
        internal static string kWfiWordFormClassLabel {
            get {
                return ResourceManager.GetString("kWfiWordFormClassLabel", resourceCulture);
            }
        }
    }
}
